### ISSUE TITLE
This really doesn't explain much

### ISSUE THREAD

**Issue by mcepl** [plan9-for-vimspace/plan9-for-vimspace#5]
https://github.com/plan9-for-vimspace/plan9-for-vimspace/blob/e968200e794914726fd342eb14c0f860c910ae3d/doc/plan9-for-vimspace.txt#L28

This is for people who don't use ACME editor, right? So, how am I supposed to know  how are mouse buttons remapped there?

**Comment by elrzn** [comment]
Huh? I'd assume that people interested in this project are versed both in ACME and vi.

It may be useful to update the docs with the following URL though http://acme.cat-v.org/mouse

**Comment by mcepl** [comment]
Well, yes, but the point what exact parts of that standard are actually implemented in the plugin?

**Comment by fmoralesc** [comment]
Sorry for the laconic documentation ;) Any improvements are appreciated. I just included a very brief description of the mappings.

**Comment by mcepl** [comment]
A way better. ``[Right click]`` looks like genuinely useful thing. Thank you.
